import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import BootstrapClient from "@/components/BootstrapClient";

/* Template CSS */
import "@/assets/css/tidytouch.css";

import Header from "@/components/Layout/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="custom-cursor">
				<div className="custom-cursor__cursor"></div>
				<div className="custom-cursor__cursor-two"></div>
				<div className="page-wrapper">
					<BootstrapClient />
					<Header />
					{children}
				</div>

				{/* Load jQuery first */}
				<Script
					src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
					strategy="beforeInteractive"
				/>
				{/* Load your template JS */}
				<Script src="/assets/js/tidytouch.js" strategy="afterInteractive" />
			</body>
		</html>
	);
}
